const FIV = 5;
const THR = 3;
let a6 = FIV % THR;
let a7 = THR % FIV;
let a8 = FIV + THR;
let a9 = FIV - THR;
let a10 = 75 + `KG`;
console.log(a6);
console.log(a7);
console.log(a8);
console.log(a9);
console.log(a10);
